name: "pre-release"

on:
  push:
    branches: [ main ]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
        node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: API_TOKEN=ci npm run makeElmEnv
      - run: npm test
      - run: npm run build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: dist/*
